name: athmovil_checkout_flutter
description: A new flutter plugin project.
version: 1.0.0
author:
homepage:

environment:
  sdk: '>=2.12.0 <4.0.0'
  #flutter: ">=1.20.0 <2.0.0"

dependencies:
  async:
  uuid:
  intl:
  flutter:
    sdk: flutter

dev_dependencies:
  meta:
  charcode:
  test_api:
  mockito:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' and Android 'package' identifiers should not ordinarily
  # be modified. They are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      android:
        package: com.evertec.athmovil.athmovil_checkout_flutter
        pluginClass: AthmovilCheckoutFlutterPlugin
      ios:
        pluginClass: AthmovilCheckoutFlutterPlugin

  # To add assets to your plugin package, add an assets section, like this:
  assets:
      - assets/
      - assets/2.0x/
      - assets/3.0x/

